### ISSUE TITLE
No access to /dev/tty on alpine or busybox toolbox images

### ISSUE THREAD

**Issue by sporkmonger** [coreos/toolbox#19]
There doesn't seem to be a writeable TTY device inside toolbox (using an Alpine image)?

Expected behavior:

```
$ echo 'test' > /dev/tty
test
```

Actual behavior:

```
$ echo 'test' > /dev/tty
-bash: /dev/tty: No such device or address
```

Works fine on fedora, but I can't think of a reason why it wouldn't work on a custom image?

**Comment by sporkmonger** [comment]
Worth noting that I can boot into the same exact image without the tty problem on the same box by just entering the docker command manually.

**Comment by sporkmonger** [comment]
Tried it with ubuntu too and that works, so may be alpine/busybox specific. Given that image size matters though, having it work with alpine still seems important.

**Comment by sporkmonger** [comment]
Confirming the problem also happens w/ busybox.

**Comment by alexanderkiel** [comment]
Same for me with alpine 3.2 in CoreOS 723.3.0
