### ISSUE TITLE
try to use busybox image, error: lacks the binary to execute

### ISSUE THREAD

**Issue by Gohan** [coreos/toolbox#22]
cat ~/.toolboxrc

```
TOOLBOX_DOCKER_IMAGE=busybox
TOOLBOX_DOCKER_TAG=ubuntu-14.04
```

toolbox --bind=/home/core

Directory /var/lib/toolbox/core-busybox-ubuntu-14.04 lacks the binary to execute or doesn't look like a binary tree. Refusing.

**Comment by crawford** [comment]
Apparently, that image doesn't come with bash. Run `toolbox /bin/sh` instead.

**Comment by marineam** [comment]
Perhaps the script should fall back to sh automatically?

**Comment by crawford** [comment]
Meh, maybe just a TOOLBOX_ENTRY variable so you don't have to type out /bin/sh every time.

**Comment by jonboulle** [comment]
+1
