### ISSUE TITLE
smartctl does not work in toolbox

### ISSUE THREAD

**Issue by llamahunter** [coreos/toolbox#53]
# Bug #

## Host Operating System Version ##

Coreos 1967.6.0

## Environment ##

bare metal

## Expected Behavior ##

Able to run smartctl commands

## Actual Behavior ##

localhost$ toolbox --bind=/dev:/dev smartctl --all /dev/sdc
Spawning container core-fedora-latest on /var/lib/toolbox/core-fedora-latest.
Press ^] three times within 1s to kill container.
smartctl 6.5 2016-05-07 r4318 [x86_64-linux-4.14.96-coreos-r1] (local build)
Copyright (C) 2002-16, Bruce Allen, Christian Franke, www.smartmontools.org

Smartctl open device: /dev/sdc failed: Operation not permitted
Container core-fedora-latest failed with error code 2.

## Reproduction Steps ##

  1. install smartmontools in toolbox
  2. run smartctl against a drive

## Other Information ##

If you create an ubuntu docker container with --privileged mode, and install run smartctl in that container, it works.  It seems to be a capabilities issue of some sort.

**Comment by QMichard** [comment]
Hi, 
I'm having the same issue. Coreos 2023.4.0 / smartctl 6.6 2017-11-05 r4594

**Comment by rata** [comment]
@QMichard @llamahunter I have no problem running it in Flatcar container linux (https://www.flatcar-linux.org/). Just need to specify the devices to bind, like:

```
toolbox --bind=/dev/sdd:/dev/sdd --bind=/dev/sde:/dev/sde  --bind=/dev/sdf:/dev/sdf --bind=/dev/sda:/dev/sda
```

**Comment by travier** [comment]
We're no longer maintaining this specific script. See https://github.com/coreos/toolbox/pull/77.
