### ISSUE TITLE
--registry-mirror flag

### ISSUE THREAD

**Issue by arman-sydikov** [coreos/toolbox#57]
# Feature Request #

Since connection to docker hub from China is very slow and unstable, is it possible to add ` --registry-mirror` flag so we can start toolbox with [the official Chinese registry mirror](https://docs.docker.com/registry/recipes/mirror) like `minikube ssh toolbox --registry-mirror=https://registry.docker-cn.com` ?

## Environment ##

Windows 10 Professional
VirtualBox

## Desired Feature ##

Add ` --registry-mirror` flag

## Other Information ##

`minikube ssh toolbox` keeps failing to pull the image with message: `Error pulling image "docker://fedora:29": unable to pull docker://fedora:29: unable to pull image: Error writing blob: error storing blob to file "/var/tmp/storage282097889/1": unexpected EOF`

**Comment by travier** [comment]
We're no longer maintaining this specific script. See https://github.com/coreos/toolbox/pull/77.
