### ISSUE TITLE
Toolbox hang for a long time and can't input any command on terminal window

### ISSUE THREAD

**Issue by chuanchang** [coreos/toolbox#64]
# Bug #
Toolbox hang for a long time and can't input any command, including ctrl+c & ctrl+z, and terminal window is dead.

## Host Operating System Version ##
RHEL-8.3

## Environment ##
# cat /etc/redhat-release
Red Hat Enterprise Linux release 8.3 Beta (Ootpa)

# git rev-parse HEAD
d510461986ff7fe8160614ba5cf179f8facacdda

What hardware/cloud provider/hypervisor is being used to run toolbox?

## Expected Behavior ##
fix it

## Actual Behavior ##

[root@ibm-x3650m4-01-vm-14 toolbox]# ./rhcos-toolbox
Error: error getting authfile /var/lib/kubelet/config.json: stat /var/lib/kubelet/config.json: no such file or directory
Would you like to manually authenticate to registry: 'registry.redhat.io' and try again? [y/N] y
Authenticating with existing credentials...
Existing credentials are valid. Already logged in to registry.redhat.io
Trying to pull registry.redhat.io/rhel8/support-tools...
Getting image source signatures
Copying blob ec1681b6a383 done
Copying blob 6b1688d3542f done
Copying blob c4d668e229cd done
Copying config 50b63c2aff done
Writing manifest to image destination
Storing signatures
50b63c2aff8c13f9f8594c9eaf5fc961f39c74df6d9c6ddde8ca705f78f3c14d

NOTE: hang forever in here, and can't input anything, the terminal window is dead.

## Reproduction Steps ##

  1. git clone https://github.com/coreos/toolbox.git
  2.  cd toolbox && ./rhcos-toolbox

## Other Information ##

RHBZ: https://bugzilla.redhat.com/show_bug.cgi?id=1882224

**Comment by travier** [comment]
Now tracked as https://bugzilla.redhat.com/show_bug.cgi?id=1877186 and should be worked-around by https://github.com/coreos/toolbox/pull/67.
