### ISSUE TITLE
Toolbox issue

### ISSUE THREAD

**Issue by gadeykarthik** [coreos/toolbox#65]
lease do not use --share-system anymore, use $SYSTEMD_NSPAWN_SHARE_* instead. Spawning container rxxxxxk-gcr.io_google-containers_toolbox-20XXXXX3-00 on /var/lib/toolbox/rxxxxxxk-gcr.io_ google-containers_toolbox-20190523-00. Press ^] three times within 1s to kill container. Failed to allocate scope: Unit rigonblick-gcr.io_google-containers_toolbox-20190523-00.scope already exists. Unable to get into toolbox can assitance want to get into it.
Failed to allocate scope: Unit rXXXXXk-gcr.io_google-containers_toolbox-20190523-00.scope already exists.
Parent died too early

**Comment by travier** [comment]
I don't think that the same toolbox we are speaking about here. Closing but feel free to reopen if you have more info.
